name: Segundo Workflow

on:
  push:

env:
    CURSO: "Integração contínua"

jobs:
  primeiro-job:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Ativ02"
      - name: Checkout
        uses: actions/checkout@v5
      - name: Exibir curso
        run: echo "${{env.CURSO}}"
      - name: Usuario
        run: whoami
      - name: Repositorio
        run: pwd
      - name: Exibir Branch Atual
        run: echo "A branch atual é ${{ github.ref_name }}"

      